// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmyhqehyesubyespegst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teWhxZWh5ZXN1Ynllc3BlZ3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjIxODMsImV4cCI6MjA2ODU5ODE4M30.F0DeTf42eIYbhXudOyiUPTpFm3AwBJO_ET6ep5YXxnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});